fbclone/apps/login/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views
urlpatterns = [
    path('home/',views.IndexView.as_view(),name="homes"),
    path('', views.PostListView.as_view(),name="home"),
    # path('', views.HomeView.as_view()),
    path('postsuccess/', views.PostSuccessView.as_view()),
    path('register', views.RegisterView.as_view(),name="register"),
    path('accounts/profile/',views.ProfileView.as_view(),name="profile"),
    path('accounts/logout/', auth_views.LogoutView.as_view(template_name='enroll/logout.html'), name='logout'),
    path('post/', views.PostView.as_view(),name="post"),
    path('postlist/', views.PostListView.as_view(),name="postlist"),
    # path('postlist/', views.PostListView.as_view(),name="postlist"),
    path('mypost/', views.MyPostView.as_view(),name="mypost"),
    path('detail/<int:id>', views.PostDetailView.as_view(),name="mypostdeatils"),
    path('update/<int:pk>', views.UpdateView.as_view(),name="updateview"),   
    path('delete/<int:pk>', views.DeleteView.as_view(),name="deleteview"),


]

fbclone/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.models import User
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('login.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

fbclone/apps/login/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Post(models.Model):
	title=models.CharField(max_length=200)
	image =models.ImageField(upload_to ='images/')
	author =models.ForeignKey(User,on_delete= models.CASCADE,null=True,blank=True)
	description=models.TextField()
	updated_at=models.DateTimeField(auto_now= True)
	created_at=models.DateTimeField(auto_now_add=True)

fbclone/apps/login/forms.py
from django.contrib.auth.forms import UserCreationForm  
from django.contrib.auth.models import User
from django import forms
from .models import Post
class SignupForm(UserCreationForm):
	class Meta:
		model=User
		fields=['username','first_name','last_name','email']

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # fields = "__all__"
        fields = ['title','image','description']
        
 

fbclone/apps/login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm  
from django.contrib.auth.models import User
from .forms import SignupForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView
from django.views.generic import TemplateView
from .forms import PostForm
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView
from .models import Post
from django.views.generic.edit import DeleteView
class IndexView(TemplateView):
    template_name='enroll/home.html'


class HomeView(TemplateView):
    template_name='enroll/homehtml.html'


class RegisterView(CreateView):
    form_class = SignupForm
    template_name='enroll/index.html'
    success_url = '/accounts/login/'
    

@method_decorator(login_required, name='dispatch')  
class PostView(CreateView):
    model= Post
    form_class = PostForm
    template_name='enroll/post.html'
    # success_url = '/postsuccess/' 
    success_url = '/postlist/'
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super(PostView,self).form_valid(form)

@method_decorator(login_required, name='dispatch')            
class ProfileView(TemplateView):
    template_name='enroll/proflie.html'


class PostSuccessView(TemplateView):
    template_name='enroll/postsuccess.html'


class HomeLoginView(TemplateView):
    template_name='enroll/homelogin.html'

class PostListView(ListView):
    model = Post
    template_name='enroll/postlist.html'
    ordering=['-created_at']
   

class MyPostView(ListView):
    model = Post
    template_name='enroll/postlist.html'
    ordering=['-created_at']
    def get_queryset(self):
        user = self.request.user
        return Post.objects.filter(author=user)

class PostDetailView(DetailView):
    model = Post
    template_name='enroll/detail.html'
    pk_url_kwarg = 'id'
    context_object_name = 'post'


class UpdateView(UpdateView):
    model = Post
    template_name='enroll/update.html'
    fields = ["title","image","description"]
    success_url ="/postlist/"


class DeleteView(DeleteView):
    model = Post
    template_name='enroll/delete.html'
    success_url ="/postlist/"
    

fbclone/templates/enroll/delete.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <link rel="stylesheet" href="{% static 'enroll/css/bootstrap.css' %}">
</head>
<body>
    <div class="container mt-5">
        <h2 class="text-center alert alert-danger">Delete</h2>
        <h1> Are You Sure ?</h1>
        <form method="post"> 
            {% csrf_token %} 
            {{ form.as_p }} 
            <input class="btn btn-warning" type="submit" value="Delete"> 
            <a class="btn btn-warning" href="{% url 'mypostdeatils' post.id %}">Cancel</a>
        </form> 
    </div>
 <script src="{% static 'enroll/js/jquery.js' %}"></script>
 <script src="{% static 'enroll/js/popper.js' %}"></script>
 <script src="{% static 'enroll/js/bootstrap.js' %}"></script>
</body>
</html>

fbclone/templates/enroll/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <link rel="stylesheet" href="{% static 'enroll/css/bootstrap.css' %}">
    <style>
        .postcenter{
            text-align: center;
        }
        img{
           text-align: center;
           margin-left: 30%;
         }
    </style>
</head>
<body>
 <div class="container mt-5">
  <h2 class="text-center alert alert-danger">Details Page {{user}}</h2>
    
        <h1 class="postcenter">{{post.title}}</h1>
        
        <img src="{{ post.image.url }}" width="400" height="200">
        <h5>Author Name :-{{post.author}}</h5>
        <p>Description :- {{post.description}}</p>
        <p>{{post.created_at}}</p>
        <hr>
        
        {% if user == post.author %}
            <a class="btn btn-warning" href="{% url 'updateview' post.id %}">Update</a>
            <a class="btn btn-warning" href="{% url 'deleteview' post.id %}">Delete</a>            
        {% endif %}
        <a class="btn btn-warning" href="{% url 'home' %}">Home</a>
        
 </div>
 <script src="{% static 'enroll/js/jquery.js' %}"></script>
 <script src="{% static 'enroll/js/popper.js' %}"></script>
 <script src="{% static 'enroll/js/bootstrap.js' %}"></script>
</body>
</html>

fbclone/templates/enroll/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <link rel="stylesheet" href="{% static 'enroll/css/bootstrap.css' %}">
</head>
<body>
 <div class="container mt-5">
  <h2 class="text-center alert alert-danger">Home Page</h2>
  
 </div>
 <script src="{% static 'enroll/js/jquery.js' %}"></script>
 <script src="{% static 'enroll/js/popper.js' %}"></script>
 <script src="{% static 'enroll/js/bootstrap.js' %}"></script>
</body>
</html>

fbclone/templates/enroll/homehtml.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <link rel="stylesheet" href="{% static 'enroll/css/bootstrap.css' %}">
 <style>
.gradient-custom {
/* fallback for old browsers */
background: #6a11cb;

/* Chrome 10-25, Safari 5.1-6 */
background: -webkit-linear-gradient(to right, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1));

/* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
background: linear-gradient(to right, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1))
}
 </style>
</head>
<body>

<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-dark text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <div class="mb-md-5 mt-md-4 pb-5">

              <h2 style="color:white;font-size:46px;" class="fw-bold mb-2 text-uppercase">Home Page</h2>
              <p class="text-white-50 mb-5">Please enter your login </p>
              <a href="/accounts/login/" class="btn btn-outline-light btn-lg px-5" type="submit">Login</a>
            </div>

            <div>
              <p class="mb-0">Don't have an account? <a href="/register" class="text-white-50 fw-bold">Sign Up</a>
              </p>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>
</body>

fbclone/templates/enroll/homelogin.html
<!-- {% load crispy_forms_tags %} -->
 <!-- {{form|crispy}} -->



<!-- # def get_queryset(self):
    #     users = self.request.user
    #     return Post.objects.filter(author=users) -->

    def form_valid(self, form):
        form.instance.user= self.request.user
        form.instance.created_by = self.request.user
        return super(PostView,self).form_valid(form)

        
 def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user

        self.object.save()
        return super(PostView,self).form_valid(form)


form = NewNewsForm(form_data)
    if form.is_valid():
        news = form.save(commit=False)
        news.author = request.user
        news.save()

fbclone/templates/enroll/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 
 <link rel="stylesheet" href="{% static 'enroll/css/bootstrap.css' %}">
</head>
<body>
 <div class="container mt-5">
  <h2 class="text-center alert alert-danger">Registration Page</h2>
  <div class="row">
     <div class="col-sm-7">
        
        <form action="" method="post">
       
         <!-- {{form.as_p}} -->

        
        {% for i in form %}
        {% csrf_token %}
        {{i.label_tag}}{{i}}{{i.errors|striptags}}<br>
        {% endfor %}
         <input type="submit" class="btn btn-warning" value="submit">
         <a class="btn btn-warning" href="/">Home</a>
      </form>
        </form>
     </div>
  

     
  </div>
 </div>
 <script src="{% static 'enroll/js/jquery.js' %}"></script>
 <script src="{% static 'enroll/js/popper.js' %}"></script>
 <script src="{% static 'enroll/js/bootstrap.js' %}"></script>
</body>
</html>

fbclone/templates/enroll/logout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
<style>
h5 {text-align: center;}

</style>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <link rel="stylesheet" href="{% static 'enroll/css/bootstrap.css' %}">
</head>
<body>
 <div class="container mt-5">
  <h2 class="text-center alert alert-danger">Logged out</h2>
  <h5>Thanks for spending some quality time with the web site today.</h5>
  <a href="/accounts/login/" class="btn btn-success">Login</a>
  <a class="btn btn-warning" href="/">Home</a>
 
 </div>
 <script src="{% static 'enroll/js/jquery.js' %}"></script>
 <script src="{% static 'enroll/js/popper.js' %}"></script>
 <script src="{% static 'enroll/js/bootstrap.js' %}"></script>
</body>
</html>

fbclone/templates/enroll/post.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <link rel="stylesheet" href="{% static 'enroll/css/bootstrap.css' %}">

</head>
<body>
 <div class="container mt-5">
     <h2 class="text-center alert alert-danger">Post Page {{user}}</h2>
     {% if user.is_authenticated %}
     <div class="container mt-5">
          <form action="" method="post" enctype="multipart/form-data">
               {% csrf_token %}
               {{form.as_p}}
             <input type="submit" class="btn btn-warning" value="submit">
             <!-- <a class="btn btn-warning" href="/">Home</a> -->
          </form>
     </div>
     {% endif %}
     
 </div>
 <script src="{% static 'enroll/js/jquery.js' %}"></script>
 <script src="{% static 'enroll/js/popper.js' %}"></script>
 <script src="{% static 'enroll/js/bootstrap.js' %}"></script>
 
</body>
</html>

fbclone/templates/enroll/postlist.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <link rel="stylesheet" href="{% static 'enroll/css/bootstrap.css' %}">
 <style>
     .postcenter{
          text-align: center;
     }
     img{
       text-align: center;
       margin-left: 30%;
     }
</style>
</head>
<body>
 <div class="container mt-5">
     {% comment %} <div class="text-center alert alert-danger">
         <h1 style="float:left;">Post Page  </h1> 
         <h4 style="color: black; float:right;">{{user}}</h4>
          <a class="btn btn-primary" href="{% url 'mypost' %}" role="button">My Post</a>
          <a class="btn btn-primary" href="{% url 'post'%}" role="button">Create Post</a>
          <a class="btn btn-primary" href="{% url 'logout' %}" role="button">Logout</a>
         
          <hr style="clear:both;"/>
     </div> {% endcomment %}
     <div class="text-center alert alert-danger">
      <h1 style="float:left;">Home Page  </h1> 
        {% if user.is_authenticated %}
          <h4 style="color: black; float:right;">{{user}}</h4>
          <a class="btn btn-primary" href="{% url 'mypost' %}" role="button">My Post</a>
          <a class="btn btn-primary" href="{% url 'post'%}" role="button">Create Post</a>
          <a class="btn btn-primary" href="{% url 'logout' %}" role="button">Logout</a>
          <hr style="clear:both;"/>
        {% else %}
          <a class="btn btn-primary" href="{% url 'login' %}" role="button">Login</a>
          <a class="btn btn-primary" href="{% url 'register' %}" role="button">Registration</a>
          <hr style="clear:both;"/>
        {% endif %}
     </div>
     {% for i in post_list %}
     <h1 class="postcenter">{{i.title}}</h1>
     <a href="{% url 'mypostdeatils' i.id %}"><img src="{{ i.image.url }}" width="400" height="200"></a>
     <h5>Author Name :-{{i.author}}</h5>
     <p>Description :- {{i.description}}</p>
     <p>{{i.created_at}}</p>
     <hr>
     {% endfor %}
 </div>
 <script src="{% static 'enroll/js/jquery.js' %}"></script>
 <script src="{% static 'enroll/js/popper.js' %}"></script>
 <script src="{% static 'enroll/js/bootstrap.js' %}"></script>
</body>
</html>

fbclone/templates/enroll/postsuccess.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <link rel="stylesheet" href="{% static 'enroll/css/bootstrap.css' %}">
</head>
<body>
 <div class="container mt-5">
      <h2 class="text-center alert alert-danger">Post Create</h2>
      <a href="/postlist/">Your Post</a>
 </div>
 <script src="{% static 'enroll/js/jquery.js' %}"></script>
 <script src="{% static 'enroll/js/popper.js' %}"></script>
 <script src="{% static 'enroll/js/bootstrap.js' %}"></script>
</body>
</html>

fbclone/templates/enroll/proflie.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <link rel="stylesheet" href="{% static 'enroll/css/bootstrap.css' %}">
</head>
<body>
 <div class="container mt-5">
  <h2 class="text-center alert alert-danger">You Are Login</h2>
  <p>Your Username is : {{user}} </p>
  <p>Your User Id is  : {{user.id}} </p>
  
  <a class="btn btn-warning" href="/post">Create Post</a>
  <a class="btn btn-warning" href="{% url 'postlist' %}">Home</a>
  <a class="btn btn-warning" href="{% url 'logout' %}">Logout</a>
      </form>
 </div>
 <script src="{% static 'enroll/js/jquery.js' %}"></script>
 <script src="{% static 'enroll/js/popper.js' %}"></script>
 <script src="{% static 'enroll/js/bootstrap.js' %}"></script>
</body>
</html>

fbclone/templates/enroll/update.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <link rel="stylesheet" href="{% static 'enroll/css/bootstrap.css' %}">
</head>
<body>
    <div class="container mt-5">
        <h2 class="text-center alert alert-danger">Update</h2>
        <form method="post"> 
            {% csrf_token %} 
            {{ form.as_p }} 
            <input type="submit" value="Update"> 
        </form> 
    </div>
 <script src="{% static 'enroll/js/jquery.js' %}"></script>
 <script src="{% static 'enroll/js/popper.js' %}"></script>
 <script src="{% static 'enroll/js/bootstrap.js' %}"></script>
</body>
</html>